### ISSUE TITLE
Visit statistics of library.kiwix.org, download.kiwix.org and download.openzim.org are not in matomo anymore

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#248]
Following yesterday migration to new storage server, we have no more visit logs uploaded to matomo for library.kiwix.org, download.kiwix.org and download.openzim.org

**Comment by kelson42** [comment]
@benoit74 It´s based on log paraing via agent. I suspect the agent is not installed or configured.

**Comment by rgaudin** [comment]
This is due to scaleway restarting old server. logrotate and import-log jobs ran on the old server instead of the new one. Log files are present on the filesystem. Everything should go back to normal tonight (happens between 01:00 and 04:00).

@benoit74 will close the ticket during next week routine.

**Comment by kelson42** [comment]
We can close this I guess

**Comment by benoit74** [comment]
Yep, we wanted to check it was still ok during weekly routine, it is now done
