### ISSUE TITLE
https://kiwix.org is not working

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#308]
While https://www.kiwix.org/ works fine and redirects to https://kiwix.org/en/, https://kiwix.org and https://kiwix.org/ are not working at all. 

Is this really intentional?

**Comment by kelson42** [comment]
This is a regression

**Comment by Popolechien** [comment]
Ok that's interesting - it works if I am logged in onto the website, and does not if I use an incognito window.

There hasn't been any update in a while, I'm kind of stumped here as to what is going on (and how to remediate this).

**Comment by kelson42** [comment]
@Popolechien Please open a ticket at the service provider.

**Comment by rgaudin** [comment]
@kelson42 the website responds (with a 500 error) ; if you meant Cyon by service provider, I doubt it's their responsibility at this stage.

![Image](https://github.com/user-attachments/assets/44444ffb-b343-44fc-8065-c5dab811f8bd)

**Comment by kelson42** [comment]
@rgaudin Who is probably responsible? You suspect one of the WP admins to have changed the conf?

**Comment by rgaudin** [comment]
Most likely. This error actually returns a `200` HTTP code and there's no detail in Cyon access log of course (and it's not in error log neither since it's an application error that returns 200`

```
196.200.90.182 - - [23/Nov/2024:19:14:35 +0100] "GET / HTTP/1.1" 200 291 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0"
```

I fixed it in the website's `.htaccess` with the following:

```
# added by rgaudin on 2024-11-23 due to https://github.com/kiwix/operations/issues/308
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule ^$ /en/ [L]
</IfModule>
```

There are many rules in this file so it might be good for WP admins to look at it. No idea for how long this went on.
