### ISSUE TITLE
Backup our website

### ISSUE THREAD

**Issue by Popolechien** [kiwix/operations#334]
Kiwix.org is running Wordpress 6.3 but the current version is Wordpress 6.7.

We should probably back it up before running any sort of update.

**Comment by rgaudin** [comment]
I've made a manual backup of the files and the DB for the one named `website2023`. DB backup can be done in Cyon UI.
FYI there are traces of a previous backup thing (not used anymore), probably a WP plugin so that might be interesting to look at.

I am closing this as we have #128 for the longer term solution.
